# Problem 2: Even Fibonacci Numbers
# # Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# ```1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...```
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

library(tictoc)

tic()
fib <- c(1, 1)
while( fib[length(fib)] < 4000000 ) {
  fib <- c(fib, (fib[length(fib)-1] + fib[length(fib)]))
}
sum( fib[ fib %% 2 == 0 ] )
toc()

# Recursive function. Based on research of other solutions
tic()
fib <- function(x, y) {
  s <- x + y
  c(s, if ( s < 4000000) fib(y, s) )
}
f <- fib(0, 1)
sum( f[ f %% 2 == 0 ] )
toc()